bench: fix conflicts with symbol `random` on osx
Drachennest/bench/bench_strtod.cc:144:22: error: redefinition of
      'random' as different kind of symbol
static JenkinsRandom random;
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include/stdlib.h:228:7: note:
      previous definition is here
long     random(void) __swift_unavailable("Use arc4random instead.");
         ^